name = "GiftExchangeRandomizer"
uuid = "cf4cfb94-92ec-4ec8-9de2-c1a6f2215adc"
authors = ["rosston <ross.brandes@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"

[compat]
julia = "1.6"
